import {DraftOptions} from "./draft.service";

export const testDraftOptions: Array<DraftOptions> = [
  {
    draftName: 'HOLAS',
    draftItems: [
      {itemName:'Orcs', itemCategory:'Faction'},
      {itemName:'Elves', itemCategory:'Faction'},
      {itemName:'Dwarves', itemCategory:'Faction'},
      {itemName:'Undead', itemCategory:'Faction'},
      {itemName:'Templar', itemCategory:'Faction'},
      {itemName:'Druid', itemCategory:'Hero'},
      {itemName:'Gorgon', itemCategory:'Hero'},
      {itemName:'Cultist', itemCategory:'Hero'},
      {itemName:'Demon Lord', itemCategory:'Hero'},
      {itemName:'Hill Giant', itemCategory:'Hero'},
    ],
    draftItemCategories: ['Faction', 'Hero'],
    picksPerPlayer: 2,
    randomDraftItems: false,
    randomDraftOrder: false,
    useItemCategories: true,
    snakeDraft: false,
    balancedDraft: false,
    numberOfPlayers: 4,
    teamDraft: true
  },
  {
    draftName: 'Tanares Adventures PvP',
    draftItems: [
      {itemName:'Test1', itemCategory:'Bruiser'},
      {itemName:'Test2', itemCategory:'Bruiser'},
      {itemName:'Test3', itemCategory:'Bruiser'},
      {itemName:'Test1', itemCategory:'Brute'},
      {itemName:'Test2', itemCategory:'Brute'},
      {itemName:'Test3', itemCategory:'Brute'},
      {itemName:'Test4', itemCategory:'Healer'},
      {itemName:'Test5', itemCategory:'Healer'},
      {itemName:'Test6', itemCategory:'Healer'},
      {itemName:'Test7', itemCategory:'Shooter'},
      {itemName:'Test8', itemCategory:'Shooter'},
      {itemName:'Test9', itemCategory:'Shooter'},
      {itemName:'Test10', itemCategory:'Tank'},
      {itemName:'Test11', itemCategory:'Tank'},
      {itemName:'Test12', itemCategory:'Tank'},
      {itemName:'Test13', itemCategory:'Commander'},
      {itemName:'Test14', itemCategory:'Commander'},
      {itemName:'Test15', itemCategory:'Commander'},
      {itemName:'Test16', itemCategory:'Controller'},
      {itemName:'Test17', itemCategory:'Controller'},
      {itemName:'Test18', itemCategory:'Controller'},
      {itemName:'Test19', itemCategory:'Tactician'},
      {itemName:'Test20', itemCategory:'Tactician'},
      {itemName:'Test21', itemCategory:'Tactician'},
    ],
    draftItemCategories: ['Bruiser', 'Brute', 'Healer', 'Shooter', 'Tank', 'Commander', 'Controller', 'Tactician'],
    picksPerPlayer: 4,
    randomDraftItems: true,
    randomDraftOrder: false,
    useItemCategories: true,
    snakeDraft: false,
    balancedDraft: false,
    numberOfPlayers: 2,
    teamDraft: true
  },
  {
    draftName: 'Uprising with Heroes',
    draftItems: [
      {itemName:'Abominations', itemCategory:'Faction'},
      {itemName:'Dragonborn', itemCategory:'Faction'},
      {itemName:'Drow', itemCategory:'Faction'},
      {itemName:'Dwarves', itemCategory:'Faction'},
      {itemName:'Gnomes', itemCategory:'Faction'},
      {itemName:'High Elves', itemCategory:'Faction'},
      {itemName:'Orcs', itemCategory:'Faction'},
      {itemName:'Order of the Moon', itemCategory:'Faction'},
      {itemName:'Templar', itemCategory:'Faction'},
      {itemName:'Merfolk', itemCategory:'Faction'},
      {itemName:'Druid', itemCategory:'Hero'},
      {itemName:'Ranger', itemCategory:'Hero'},
      {itemName:'Assassin', itemCategory:'Hero'},
      {itemName:'Berserker', itemCategory:'Hero'},
      {itemName:'Cavalier', itemCategory:'Hero'},
      {itemName:'Sorcerer', itemCategory:'Hero'},
      {itemName:'Cleric', itemCategory:'Hero'},
      {itemName:'Forge Master', itemCategory:'Hero'},
      {itemName:'Flesh Titan', itemCategory:'Hero'},
      {itemName:'Harpy Queen', itemCategory:'Hero'},
      {itemName:'Gnome Tinkerer', itemCategory:'Hero'},
    ],
    draftItemCategories: ['Faction', 'Hero'],
    picksPerPlayer: 2,
    randomDraftItems: true,
    randomDraftOrder: false,
    useItemCategories: true,
    snakeDraft: true,
    balancedDraft: false,
    numberOfPlayers: 4,
    teamDraft: true
  },
]