import { CastType, EffectTokenType, IconHtml, SpellCard, Region } from "./spell-card-data";

export const UprisingTacticsSpellCards: Array<SpellCard> = [
  {
    name: 'Entangle',
    spellCost: 1,
    htmlDescription: `<p>Select two regions and place an ${IconHtml.Entangle} token on each. You may add a -${IconHtml.SlowHaste} token to any units in each
      of the selected regions if it is a Forest or Hills region. You may add a -${IconHtml.StrengthenWeaken} token to any units in each of the selected regions if 
      it is a Marsh or Badlands region.</p>`,
    effectTokens: [EffectTokenType.Entangle, EffectTokenType.Slow, EffectTokenType.Weaken],
    regions: [Region.Forest, Region.Hills, Region.Marsh, Region.Badlands],
    castType: CastType.Normal,
    destructive: false 
  },
  { 
    name: 'Holy Light',
    spellCost: 2,
    htmlDescription: `<p>Heal 2 on each unit you control. You may remove 1 effect token from each unit you control.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false,
    healing: true
  },
  { 
    name: 'Cure Light Wounds',
    spellCost: 1,
    htmlDescription: `<p>If the defending unit is not destroyed at the end of this battle, <i>Heal 2</i>.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
    healing: true
  },
  { 
    name: 'Invisibility',
    spellCost: 1,
    htmlDescription: `<p>After attack dice are rolled, you may force the attacking player to reroll one die.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
    healing: true
  },
  { 
    name: 'Divine Intervention',
    spellCost: 2,
    htmlDescription: `<p>Choose a region. Each unit in that region and in adjacent regions <i>Heals 2</i>.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
    healing: true
  },
  { 
    name: 'Raise Dead',
    spellCost: 2,
    htmlDescription: `<p>If the defending unit is destroyed at the end of this battle, you may perform a free recruit action.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false 
  },
  { 
    name: 'Meteor Storm',
    spellCost: 4,
    htmlDescription: `<p>Choose a region. Attack all units and buildings in that region and each adjacent region with 4 ${IconHtml.Damage}</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: true 
  },
  { 
    name: 'Chain Lightning',
    spellCost: 3,
    htmlDescription: `<p>Deal 1 damage to an enemy unit. If that unit is destroyed, you may repeat this process.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: true 
  },
  { 
    name: 'Fireball',
    spellCost: 4,
    htmlDescription: `<p>Attack an enemy unit or building with 8 ${IconHtml.Attack}. This spell may not target an enemy capitol.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: true 
  },
  { 
    name: 'Blinding Light',
    spellCost: 1,
    htmlDescription: `<p>The attacking unit attacks with -2 ${IconHtml.Attack}.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false 
  },
  { 
    name: 'Withering Curse',
    spellCost: 2,
    htmlDescription: `<p>Add a -${IconHtml.SlowHaste} and a -${IconHtml.StrengthenWeaken} token to the attacking unit.</p>`,
    effectTokens: [EffectTokenType.Slow, EffectTokenType.Weaken],
    regions: null,
    castType: CastType.Combat,
    destructive: false 
  },
  { 
    name: 'Giant Strength',
    spellCost: 1,
    htmlDescription: `<p>The attacking unit attacks with +2 ${IconHtml.Attack}.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false
  },
  { 
    name: 'Flood',
    spellCost: 1,
    htmlDescription: `<p>Place a water token on an unoccupied region. You may place a -${IconHtml.SlowHaste} token on a unit adjacent to this region.</p>`,
    effectTokens: [EffectTokenType.Slow],
    regions: [Region.Water],
    castType: CastType.Normal,
    destructive: false 
  },
  { 
    name: 'Magic Armor',
    spellCost: 1,
    htmlDescription: `<p>The attacked unit gains the <i>Armored</i> ability. The attacking unit loses the <i>Magic Attack</i> ability.</p>`,
    effectTokens: null,
    regions: [Region.Water],
    castType: CastType.Normal,
    destructive: false
  },
  { 
    name: 'Memory Recall',
    spellCost: 1,
    htmlDescription: `<p>Return any one spell card from the discard pile to your hand <b>or</b> search the spell card deck for any one spell card and add it to your hand.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false
  },
  { 
    name: 'Cloud Kill',
    spellCost: 4,
    htmlDescription: `<p>Deal 2 damage to all units.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: true
  }, 
  {
    name: "Command Stone",
    spellCost: 3,
    htmlDescription: `<p>Perform a free build action. The building created through this build action may be added to any region on the map.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: "Saving Grace",
    spellCost: 1,
    htmlDescription: `<p>At the end of this battle, the defending unit is not destroyed. This unit is set to 1 health. You may move the defending unit to an unoccupied region adjacent to a city of capitol you control.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: "Vampiric Touch",
    spellCost: 2,
    htmlDescription: `<p>The attacking unit heals for the amount of damage it dealt at the end of this battle.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: "Anti-magic Field",
    spellCost: 1,
    htmlDescription: `<p>Cancel the effect of your opponent's combat spell.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: "Second Wind",
    spellCost: 3,
    htmlDescription: `<p>After this battle, the attacking unit may attack again, starting a new battle.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: "Arcane Armiments",
    spellCost: 1,
    htmlDescription: `<p>The attacking unit gains the <i>Magic Attack</i> ability.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: "Leap Through Space",
    spellCost: 1,
    htmlDescription: `<p>At the end of the battle, you may move the unit you control in this battle (attacker or defender) up to two regions away. This does not trigger opportunity attacks.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: "Spiked Shell",
    spellCost: 1,
    htmlDescription: `<p>If the attacking unit is adjacent to the defending unit, the attacking units takes 1 damage at the end of the battle.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: "Reverse Time",
    spellCost: 1,
    htmlDescription: `<p>After the attack dice are rolled, you may choose to re-roll all of the attack dice.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: "Time Mastery",
    spellCost: 5,
    htmlDescription: `<p>At the end of this turn, you may take an addition turn.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: "Starfall",
    spellCost: 4,
    htmlDescription: `<p>Choose a player. Attack each unit that player controls with 3 ${IconHtml.Attack}.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: "Frost Lance",
    spellCost: 3,
    htmlDescription: `<p>Attack a unit with 3 ${IconHtml.Attack}. You may add a -${IconHtml.SlowHaste} token to that unit</p>`,
    effectTokens: [EffectTokenType.Slow],
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: "Summon Elemental",
    spellCost: 3,
    htmlDescription: `<p>Attack a unit adjacent to a mountain or water region with 4 ${IconHtml.Attack}.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: "Counter Attack",
    spellCost: 3,
    htmlDescription: `<p>At the end of the battle, if the defending unit is still alive, it may attack the attacking unit, starting a new battle.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: "Vortex",
    spellCost: 3,
    htmlDescription: `<p>Move any unit to an unoccupied region adjacent to a city or capitol of that units controller.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: "Sap Strength",
    spellCost: 4,
    htmlDescription: `<p>Choose a player. Add a -${IconHtml.StrengthenWeaken} token on each unit that player controls.</p>`,
    effectTokens: [EffectTokenType.Weaken],
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: "Bolster Morale",
    spellCost: 4,
    htmlDescription: `<p>Choose a player. Add a +${IconHtml.StrengthenWeaken} token on each unit that player controls.</p>`,
    effectTokens: [EffectTokenType.Strengthen],
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: "Mirror Reflection",
    spellCost: 3,
    htmlDescription: `<p>At the end of the battle, the attacking unit is dealt damage equal to the damage dealt to the defending unit.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: "Lightning Bolt",
    spellCost: 2,
    htmlDescription: `<p>Deal 1 damage to the attacking or defending unit.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: "Shock",
    spellCost: 2,
    htmlDescription: `<p>At the end of the battle, add a ${IconHtml.Shock} token to the attacking or defending unit.</p>`,
    effectTokens: [EffectTokenType.Stun],
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: "Dark Bargin",
    spellCost: 1,
    htmlDescription: `<p>The attacking unit gains 3 ${IconHtml.Attack}. The attacking unit takes 1 damage at the end of the battle.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: 'Egress',
    spellCost: 1,
    htmlDescription: `<p>Return the attacked unit to an unoccupied region adjacent to its controller's capitol.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: 'Frost Nova',
    spellCost: 4,
    htmlDescription: `<p>Choose a region. Attack each unit up to 2${IconHtml.Range} from the chosen region with 3${IconHtml.Attack}. Add a -${IconHtml.SlowHaste} token to each unit attacked using this spell that did not receive damage.</p>`,
    effectTokens: [EffectTokenType.Slow],
    regions: null,
    castType: CastType.Normal,
    destructive: true,
  },
  {
    name: 'Elemental Mastery',
    spellCost: 4,
    htmlDescription: `<p>You may add a +${IconHtml.StrengthenWeaken} a unit. You may repeat this process for the following tokens: -${IconHtml.StrengthenWeaken}, -${IconHtml.SlowHaste}, +${IconHtml.SlowHaste}, ${IconHtml.Shock}</p>`,
    effectTokens: [EffectTokenType.Strengthen, EffectTokenType.Weaken, EffectTokenType.Slow, EffectTokenType.Haste, EffectTokenType.Stun],
    regions: null,
    castType: CastType.Normal,
    destructive: true,
  },
  {
    name: 'Lightning Storm',
    spellCost: 3,
    htmlDescription: `<p>Choose a region. Add a ${IconHtml.Shock} token to each unit up to 2${IconHtml.Range} from the chosen region.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: true,
  },
  {
    name: 'Fog',
    spellCost: 2,
    htmlDescription: `<p>Time: 4. Enemy units and buildings do not perform <i>Opportunity Attacks</i> and have -1 ${IconHtml.Range} to a minimum of 1.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: true,
  },
  {
    name: 'Anti-Magic Field',
    spellCost: 3,
    htmlDescription: `<p>Time: 4. Enemy spell attacks and <i>Magic Attacks</i> only hit when a 6 is rolled.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: true,
  },
  {
    name: "Healing Rain",
    spellCost: 4,
    htmlDescription: `<p>Time: 4. Each unit you control <i>Heals 1</i> at the start of your turn.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: 'Web',
    spellCost: 3,
    htmlDescription: `<p>Time: 4. Enemy units lose the <i>Flying</i> ability.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: 'Mythril Mail',
    spellCost: 3,
    htmlDescription: `<p>Time: 3. Units you control have the <i>Armored</i> ability.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: 'Infernal Contract',
    spellCost: 3,
    htmlDescription: `<p>Time: 3. Units you control gain +2 ${IconHtml.Attack} and +1 ${IconHtml.SlowHaste}. Deal 1 damage to each unit you control at the end of each of your turns.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: 'Acid Rain',
    spellCost: 4,
    htmlDescription: `<p>Time: 3. At the end of your turn, you may attack an enemy unit or building with 2 ${IconHtml.Attack}.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: true,
  },
  {
    name: 'Mind Control',
    spellCost: 3,
    htmlDescription: `<p>Choose a unit. You may perform a free martial action using only the chosen unit.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: 'Living Walls',
    spellCost: 1,
    htmlDescription: `<p>You may move each non-capitol building you control up to two regions away from it's current region.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: 'Instant Transmission',
    spellCost: 3,
    htmlDescription: `<p>Choose a unit. Move this unit to any unoccupied region. If an enemy unit is chosen, you must pay 1 additional mana.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: 'Exchange Fates',
    spellCost: 2,
    htmlDescription: `<p>Choose a unit you control. Exchange the chosen unit's position with the unit you control in this battle. The chosen unit is now the unit participating in this battle.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: 'Tranquility',
    spellCost: 3,
    htmlDescription: `<p>Remove all <i>Effect Tokens</i> from all units and buildings.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: false,
  },
  {
    name: `Assassin's Blade`,
    spellCost: 1,
    htmlDescription: `<p>The attacking unit may only attack with 1${IconHtml.Attack}. If this attack deals any damage the defending unit is destroyed.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: `Flame Wave`,
    spellCost: 4,
    htmlDescription: `<p>Choose a region. Attack all  units and buildings in a straight line from that region with 3${IconHtml.Attack}.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: true,
  },
  {
    name: `Painful Lesson`,
    spellCost: 2,
    htmlDescription: `<p>Deal 1 damage to each enemy unit or building with an <i>Effect Token</i> on it.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: true,
  },
  {
    name: `Magic Missile`,
    spellCost: 4,
    htmlDescription: `<p>Using this spell, you may not attack the same unit or building more than once. Attack a unit with 4${IconHtml.Attack}. Attack a unit with 3${IconHtml.Attack}. Attack a unit with 2${IconHtml.Attack}.</p>`,
    effectTokens: null,
    regions: null,
    castType: CastType.Normal,
    destructive: true,
  },
  {
    name: `Frost Armor`,
    spellCost: 1,
    htmlDescription: `<p>If the defending unit is dealt damage in this battle, add a -${IconHtml.SlowHaste} token to the attacking unit.</p>`,
    effectTokens: [EffectTokenType.Slow],
    regions: null,
    castType: CastType.Combat,
    destructive: false,
  },
  {
    name: `Forked Lignhtning`,
    spellCost: 4,
    htmlDescription: `<p>Choose two units. Attack each of the chosen units with 3${IconHtml.Attack} and place a ${IconHtml.Shock} token on each of the chosen units.</p>`,
    effectTokens: [EffectTokenType.Stun],
    regions: null,
    castType: CastType.Normal,
    destructive: true,
  },
  {
    name: `Choking Vines`,
    spellCost: 3,
    htmlDescription: `<p>Choose a region. Add a ${IconHtml.Entangle} token to that region. You may add a -${IconHtml.SlowHaste} and -${IconHtml.Shock} token a unit in that region.</p>`,
    effectTokens: [EffectTokenType.Entangle, EffectTokenType.Slow, EffectTokenType.Weaken ],
    regions: null,
    castType: CastType.Normal,
    destructive: true,
  },
]