import { IconHtml } from "../uprising/spell-cards/spell-card-data";

export interface UprisingTacticsUnit {
    name: string,
    cost?: UnitCost,
    attack?: number,
    speed: number,
    attackDistance: number,
    isBuilding: boolean,
    health: number,
    specialAbilities?: Array<SpecialAbilities>,
    specialDescripton?: string,
}

interface UnitCost {
    mana?: number,
    gold?: number,
    technology?: number,
}

enum SpecialAbilities {
    FLYING = 'Flying',
    MAGIC_ATTACK = 'Magic Attack',
    RANGED_ATTACK = 'Ranged Attack',
    SEIGE_ATTACK = 'Siege Attack',
    ARMORED = 'Armored',
}

export interface VersionedUprisingTacticsUnits {
    version: string,
    units: Array<UprisingTacticsUnit>,
}

export const versionedUprisingTacticsUnits: Array<VersionedUprisingTacticsUnits> = [ 
  {
    version: '1.0.0',
    units: [
        {
            name: 'Warrior',
            cost : { gold: 8 },
            attack: 3,
            speed: 2,
            health: 3,
            attackDistance: 1,
            isBuilding: false,  
            specialAbilities: [SpecialAbilities.ARMORED],
        },
        {
            name: 'Archer',
            cost : { gold: 10 },
            attack: 3,
            speed: 3,
            health: 3,
            attackDistance: 2,
            isBuilding: false,  
            specialAbilities: [SpecialAbilities.RANGED_ATTACK],
            specialDescripton: `-1 ${IconHtml.Attack} when <i>engaged</i>.`
        },
        {
            name: 'Air',
            cost : { gold: 8, mana: 1 },
            attack: 3,
            speed: 3,
            health: 3,
            attackDistance: 2,
            isBuilding: false,  
            specialAbilities: [SpecialAbilities.FLYING],
        },
        {
            name: 'Mage',
            cost : { gold: 8, mana: 2 },
            attack: 5,
            speed: 2,
            health: 2,
            attackDistance: 1,
            isBuilding: false,  
            specialAbilities: [SpecialAbilities.MAGIC_ATTACK],
        },
        {
            name: 'Cavalry',
            cost : { gold: 8, technology: 1 },
            attack: 4,
            speed: 4,
            health: 4,
            attackDistance: 1,
            isBuilding: false,  
            specialAbilities: [],
        },
        {
            name: 'Siege Engine',
            cost : { gold: 8, technology: 2 },
            attack: 3,
            speed: 1,
            health: 3,
            attackDistance: 3,
            isBuilding: false,  
            specialAbilities: [SpecialAbilities.SEIGE_ATTACK],
            specialDescripton: `-2 ${IconHtml.Attack} when <i>engaged</i>.`
        },
        {
            name: 'Tower',
            cost : { gold: 8 },
            attack: 3,
            speed: 0,
            health: 3,
            attackDistance: 2,
            isBuilding: true,  
            specialAbilities: [],
        },
        {
            name: 'Farm',
            cost : { gold: 3 },
            attack: 3,
            speed: 0,
            health: 3,
            attackDistance: 2,
            isBuilding: true,  
            specialAbilities: [],
        },
        {
            name: 'City',
            cost : { gold: 3 },
            attack: 3,
            speed: 0,
            health: 3,
            attackDistance: 2,
            isBuilding: true,  
            specialAbilities: [],
        },
        {
            name: 'Capitol',
            attack: 5,
            speed: 0,
            health: 3,
            attackDistance: 2,
            isBuilding: true,  
            specialAbilities: [],
        },
    ]
  },  
  {
    version: '1.1.0',
    units: [
        {
            name: 'Warrior',
            cost : { gold: 8 },
            attack: 3,
            speed: 2,
            health: 3,
            attackDistance: 1,
            isBuilding: false,  
            specialAbilities: [SpecialAbilities.ARMORED],
        },
        {
            name: 'Archer',
            cost : { gold: 10 },
            attack: 3,
            speed: 3,
            health: 3,
            attackDistance: 2,
            isBuilding: false,  
            specialAbilities: [SpecialAbilities.RANGED_ATTACK],
            specialDescripton: `-1 ${IconHtml.Attack} when <i>engaged</i>.`
        },
        {
            name: 'Air',
            cost : { gold: 8, mana: 1 },
            attack: 3,
            speed: 3,
            health: 3,
            attackDistance: 2,
            isBuilding: false,  
            specialAbilities: [SpecialAbilities.FLYING],
        },
        {
            name: 'Mage',
            cost : { gold: 8, mana: 2 },
            attack: 5,
            speed: 2,
            health: 2,
            attackDistance: 1,
            isBuilding: false,  
            specialAbilities: [SpecialAbilities.MAGIC_ATTACK],
        },
        {
            name: 'Cavalry',
            cost : { gold: 8, technology: 1 },
            attack: 4,
            speed: 4,
            health: 4,
            attackDistance: 1,
            isBuilding: false,  
            specialAbilities: [],
        },
        {
            name: 'Siege Engine',
            cost : { gold: 8, technology: 2 },
            attack: 3,
            speed: 1,
            health: 3,
            attackDistance: 3,
            isBuilding: false,  
            specialAbilities: [SpecialAbilities.SEIGE_ATTACK],
            specialDescripton: `-2 ${IconHtml.Attack} when <i>engaged</i>.`
        },
        {
            name: 'Tower',
            cost : { gold: 8 },
            attack: 3,
            speed: 0,
            health: 3,
            attackDistance: 2,
            isBuilding: true,  
            specialAbilities: [],
        },
        {
            name: 'Farm',
            cost : { gold: 3 },
            attack: 2,
            speed: 0,
            health: 3,
            attackDistance: 1,
            isBuilding: true,  
            specialAbilities: [],
        },
        {
            name: 'City',
            cost : { gold: 3 },
            attack: 2,
            speed: 0,
            health: 3,
            attackDistance: 1,
            isBuilding: true,  
            specialAbilities: [],
        },
        {
            name: 'Capitol',
            attack: 5,
            speed: 0,
            health: 8,
            attackDistance: 1,
            isBuilding: true,  
            specialAbilities: [],
        },
    ]
  },  
];